mvc-app/Models/MyJob/Partial/pv_AddressDetailModel.cs
namespace mvc_app.Models.MyJob.Partial
{
    public class pv_AddressDetailModel
    {
        public string? StreetAddress { get; set; }
    }
}

mvc-app/Models/MyJob/RequestModel/AddressRequestModel.cs
namespace mvc_app.Models.MyJob.RequestModel
{
    public class AddressRequestModel
    {
        public string? City { get; set; }
        public string? State { get; set; }
        public string? PostCode { get; set; }
    }
}

mvc-app/Models/MyJob/ViewModels/AddressViewModel.cs
namespace mvc_app.Models.MyJob.ViewModels
{
    public class AddressViewModel
    {
        public string? City { get; set; }
        public string? State { get; set; }
        public string? PostCode { get; set; }
    }
}

mvc-app/Controllers/MyJobController.cs
using Microsoft.AspNetCore.Mvc;
using mvc_app.Models.MyJob.RequestModel;
using mvc_app.Models.MyJob.ViewModels;
using System.ComponentModel;
using System.Net;
using System.Text.Json.Serialization;
using System.Text.Json;
using mvc_app.Sample.Utils;
using mvc_app.Sample.Config;
using Microsoft.CodeAnalysis.Options;
using Microsoft.Extensions.Options;
using System.Configuration;
using mvc_app.Sample.Other;

namespace mvc_app.Controllers
{

    // コントローラに属性ルーティングを設定すると、規則ルーティングより優先されるみたい？
    // https://learn.microsoft.com/ja-jp/aspnet/core/mvc/controllers/routing?view=aspnetcore-6.0#mixed-routing-attribute-routing-vs-conventional-routing 
    [Route("[controller]")]
    public class MyJobController : Controller
    {
        IDateTime _dateTime;
        IConfiguration _configuration;


        public MyJobController(IDateTime datetime, IConfiguration configuration)
        {
            _dateTime = datetime;
            _configuration = configuration;
        }


        [NonAction]
        public string NoIndex()
        {
            // NonAction属性によりアクションから無視される 
            return "hello world!";
        }

        [HttpGet]
        [Route("/[controller]")]
        [Route("[action]")]
        public IActionResult Index()
        {
            // ビューに渡せる。ViewDataも同様
            ViewBag.Name = "sato";
            ViewData["Message"] = "hello world!";

            // コントローラからのDI
            System.Diagnostics.Debug.WriteLine($"Index:{_dateTime.Now}");

            // appsettings.json より取得、初期処理はデフォルトで実行されている
            // todo 全域で使いたいがどうする
            System.Diagnostics.Debug.WriteLine("cn: " + _configuration.GetConnectionString("mvc_appContext"));
            System.Diagnostics.Debug.WriteLine("name: " + _configuration.GetValue<string>("UserSettings:DefaultUser:Name"));
            System.Diagnostics.Debug.WriteLine("name: " + _configuration["UserSettings:DefaultUser:Name"]);

            // todo DIの調査が必要
            var p = new Person("sato");

            // 
            System.Diagnostics.Debug.WriteLine("setting: "+ AppSetting.Instance.GetValue<string>("UserSettings:DefaultUser:Name"));



            // 名前を付けるとViews/{controller}/{名前}.cshatml
            // 名前を付けないとViews/{controller}/{action}.cshtml
            return View("Index");   
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult InputAddressForm([FromServices] IDateTime datetime)
        {
            // di
            System.Diagnostics.Debug.WriteLine($"InputAddressForm:{_dateTime.Now}");

            return View("InputAddressForm");
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult Address(string address)
        {
            System.Diagnostics.Debug.WriteLine(address);
            return View("Address", address);
        }


        [HttpPost]
        [Route("[action]")]
        public IActionResult AddressPost(AddressRequestModel req)
        {
            // todo biz で何らかの処理後にViewModelを作成
            // var vm = (AddressViewModel)xxxBiz(req);
            System.Diagnostics.Debug.WriteLine(req);

            return View("AddressPost", new AddressViewModel {
                City = req.City,
                State = req.State,
                PostCode = req.PostCode,
            });
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult FakeApi()
        {
            // mvc画面からjsonを返す
            return new JsonResult(
                new 
                {
                    Name = "sato",
                    Age= 30
                },
                new JsonSerializerOptions
                {
                    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
# if DEBUG
                    WriteIndented = true,
# endif
                });
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult ReturnOk()
        {
            return Ok("return ok!");
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult ReturnBadRequest()
        {
            return BadRequest("return 404 error!");
        }

        [HttpGet]
        [Route("[action]")]
        public RedirectToActionResult RedirectHomeIndex()
        {
            return RedirectToAction(actionName:"Index", controllerName:"Home");
        }

        [HttpGet]
        [Route("[action]")]
        public RedirectToActionResult RedirectMyjobIndex()
        {
            return RedirectToAction("Index");
        }
    }
}

mvc-app/Views/MyJob/Address.cshtml
@model string

<h1>@Model</h1>

mvc-app/Views/MyJob/AddressPost.cshtml
@model mvc_app.Models.MyJob.ViewModels.AddressViewModel

<div>
    <p>@Model.PostCode</p>
    <p>@Model.City</p>
    <p>@Model.State</p>
</div>

mvc-app/Views/MyJob/Index.cshtml
@{
    ViewData["Title"] = "MyJobIndex";
}

<h1>@ViewData["Title"] Page</h1>
<hr />

<div>
    <!-- ________________________________________ link -->
    <p class="badge bg-primary text-wrap fs-5 p-md-2">Linkビュー</p>
    <p>
        <a asp-controller="Myjob" asp-action="InputAddressForm">InputAddressForm</a>
    </p>

    <p>
        <a asp-controller="MyJob" asp-action="RedirectHomeIndex">RedirectHomeIndex</a><br />
        <a asp-controller="MyJob" asp-action="RedirectMyjobIndex">RedirectMyjobIndex</a>
    </p>


    <!-- ________________________________________ 部分ビュー-->
    <p class="badge bg-primary text-wrap fs-5 p-md-2">部分ビュー</p>

    <!-- タグヘルパーパラメータなし -->
    <partial name="_pv_AddressDetail_0" />

    <!-- htmlヘルパー、stringパラメータを渡す-->
    @await Html.PartialAsync("_pv_AddressDetail_1", "tokyo")

    <!-- htmlヘルパー、modelパラメータを渡す-->
    @await Html.PartialAsync("_pv_AddressDetail_2", new mvc_app.Models.MyJob.Partial.pv_AddressDetailModel
    {
        StreetAddress = "1-2-3"
    })

    <hr />
    <!-- ________________________________________ 他、ViewData,ViewBag,loop -->
    <div>
        <p>message: @ViewData["Message"]</p>
        <p>name: @ViewBag.Name</p>
    </div>
    <div>
        <ul>
            @* Razor loop *@
            @for (int i = 0; i < 3; i++)
            {
                @if (i == 1)
                {
                    <li>item_@i (★)</li>
                }
                else
                {
                    <li>item_@i</li>
                }
            }
        </ul>
    </div>
</div>

mvc-app/Views/MyJob/InputAddressForm.cshtml
@model mvc_app.Models.MyJob.RequestModel.AddressRequestModel

<h1>Input For Address</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddressPost">
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PostCode" class="control-label"></label>
                <input asp-for="PostCode" class="form-control" />
            </div>
                
            <div class="form-group">
                <input type="submit" value="PostAddress" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>